; LoRa Tracker keyless repeater firmware builds.

[platformio]
src_dir = .
build_dir = ../.pio-build/repeater-firmware

[env]
platform = espressif32 @ 6.7.0
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+

[env:heltec_wifi_lora_32_v2]
board = heltec_wifi_lora_32_V2
build_flags =
  -D BOARD_HELTEC_V2
lib_deps =
  sandeepmistry/LoRa @ 0.8.0

[env:heltec_wireless_tracker]
board = esp32-s3-devkitc-1
build_flags =
  -D BOARD_WIRELESS_TRACKER
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  jgromes/RadioLib @ 6.6.0
